apiVersion: skaffold/v2beta29
kind: Config

build:
  artifacts:
    - image: lns-operator
  local:
    useBuildkit: true
    useDockerCLI: true
    # tagPolicy:
    #   sha256: {}

deploy:
  kustomize:
    paths:
      - k8s/base
